# CI/CD for Github Actions
# @author Denis Zholob (deniszholob.com)
# Checks linting, builds app
# ====================================== #

name: Build Test Branch

# Controls when the workflow will run
on:
    # Run on pushes when its not master or main
    push:
        branches-ignore:
            - 'master'
            - 'main'
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - uses: actions/setup-node@v3
              with:
                  node-version: '18.19.1'
                  cache: 'pnpm'

            - name: Get npm cache directory
              id: npm-cache-dir
              run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

            - name: Cache node modules
              id: npm-cache
              uses: actions/cache@v3
              with:
                  path: ${{steps.npm-cache-dir.outputs.dir}}
                  key: ${{runner.os}}-node-${{hashFiles('**/pnpm-lock.yaml')}}
                  restore-keys: |
                      ${{runner.os}}-node-
                      ${{runner.os}}-

            - name: Install NPM Dependencies
              run: pnpm run i

            - name: Check lint
              run: pnpm run lint

            - name: Build
              run: sh ./.github/ci/build.sh # Generates the dist folder with built angular app

            # Save dist artifacts for deployment jobs
            # https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs
            - name: Archive web demo build
              if: success()
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: dist/browser # Directory to push to GitHub Pages
