name: Test Workflow

# Manually trigger by going to this workflow in the repository actions tab
on: workflow_dispatch

jobs:
    # Install Dependencies (Base Job)
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - uses: actions/setup-node@v3
              with:
                  node-version: '18.19.1'
                  cache: 'pnpm'

            - name: Cache node modules
              id: npm-cache
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install Dependencies
              run: pnpm install

            # Save node_modules as artifact to share with dependent jobs
            - name: Cache node_modules for subsequent jobs
              uses: actions/upload-artifact@v3
              with:
                  name: node_modules
                  path: node_modules

    # Lint Job
    lint:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Download node_modules
              uses: actions/download-artifact@v3
              with:
                  name: node_modules
                  path: node_modules

            - name: Run Lint
              run: pnpm run lint

    # Prettier Format Job
    prettier:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Download node_modules
              uses: actions/download-artifact@v3
              with:
                  name: node_modules
                  path: node_modules

            - name: Run Prettier
              run: pnpm run format

    # Jest Unit Tests Job
    jest-tests:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Download node_modules
              uses: actions/download-artifact@v3
              with:
                  name: node_modules
                  path: node_modules

            - name: Run Jest Tests
              run: pnpm run test:ci

    # Storybook Tests Job
    storybook-tests:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Download node_modules
              uses: actions/download-artifact@v3
              with:
                  name: node_modules
                  path: node_modules

            - name: Run Storybook Tests
              run: pnpm run test:storybook

    # Build Job
    build:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Download node_modules
              uses: actions/download-artifact@v3
              with:
                  name: node_modules
                  path: node_modules

            - name: Build Angular App
              run: sh ./.github/ci/build.sh

            - name: Archive Build Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: dist/browser
